### PR TITLE
[Server Bug]: app.logo is not used in code

### LINKED ISSUE #6376: [Server Bug]: `app.logo` is not used in code
### Description

Currently, when trying to edit the logo, i see hardcoded references to `/img/pixelfed-icon-color.png` and `/img/pixelfed-icon-color.svg`, while `config/app.php` contains a `logo` field that points to the same, but isn't used anywhere.

It would be nice that all the hard-coded references would start using this field (and/or another field for the svg/png variant), so that it could be easily changable.

### Steps to reproduce

N/A

### Pixelfed version

0.12.6

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by rm-yakovenko**
This PR covers server-side and client-side templates. 

I did a brief testing and the main functionality (creating posts and stories) worked. LMK if something is incorrect or broken.

Fixes #6376.

### CODE REVIEW

File: app/Services/LandingService.php [hunk 1]
```diff
@@ -56,6 +56,7 @@ public static function get($json = true)
             'open_registration' => (bool) $openReg,
             'curated_onboarding' => (bool) config_cache('instance.curated_registration.enabled'),
             'version' => config('pixelfed.version'),
+            'logo' => config('app.log'),
```
Comment (dansup) [inline app/Services/LandingService.php]: typo

**Review by dansup — CHANGES_REQUESTED** [review]

**Review by dansup — APPROVED** [review]
